# Generated by Django 5.2.4 on 2026-04-05 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='confirmed', max_length=20)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_meet_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField()),
            ],
            options={
                'db_table': 'bookings_answer',
            },
        ),
        migrations.CreateModel(
            name='BookingAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], max_length=30)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookings_audit',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('timezone', models.CharField(max_length=50)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings_invitee',
            },
        ),
    ]
