# Generated by Django 5.2.4 on 2026-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_1h_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="reminder_24h_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
