# Generated by Django 5.2.4 on 2026-06-20 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reminder_1h_task_id_and_more'),
        ('events', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-start_time', 'id'], name='idx_booking_cursor_pagination'),
        ),
    ]
